-- ============================================================
-- Populate dim_city -- 
-- ============================================================

INSERT INTO dim_city (city_id, city_name, country, region) VALUES
(1,  'Brisbane',               'Australia',      'APAC'),
(2,  'Rotterdam',               'Netherlands',    'Europe'),
(3,  'Cologne',                 'Germany',        'Europe'),
(4,  'Malaga',                  'Spain',          'Europe'),
(5,  'Warsaw',                  'Poland',         'Europe'),
(6,  'Monterrey',               'Mexico',         'North America'),
(7,  'Paris',                   'France',         'Europe'),
(8,  'São Paulo',               'Brazil',         'South America'),
(9,  'Cardiff',                 'United Kingdom', 'Europe'),
(10, 'Lisbon',                  'Portugal',       'Europe'),
(11, 'Hong Kong',               'Hong Kong (China)', 'APAC'),
(12, 'Helsinki',                'Finland',        'Europe'),
(13, 'Barcelona',               'Spain',          'Europe'),
(14, 'Heerenveen',              'Netherlands',    'Europe'),
(15, 'Ottawa',                  'Canada',         'North America'),
(16, 'Incheon',                 'South Korea',    'APAC'),
(17, 'Puebla',                  'Mexico',         'North America'),
(18, 'Shanghai',                'China',          'APAC'),
(19, 'Lyon',                    'France',         'Europe'),
(20, 'Berlin',                  'Germany',        'Europe'),
(21, 'New York City',           'USA',            'North America'),
(22, 'Rimini',                  'Italy',          'Europe'),
(23, 'Johannesburg',            'South Africa',   'Africa'),
(24, 'Riga',                    'Latvia',         'Europe'),
(25, 'Buenos Aires',            'Argentina',      'South America'),
(26, 'Stockholm',               'Sweden',         'Europe'),
(27, 'Jakarta',                 'Indonesia',      'APAC'),
(28, 'Sydney',                  'Australia',      'APAC'),
(29, 'Hangzhou',                'China',          'APAC'),
(30, 'New Delhi',               'India',          'APAC'),
(31, 'Chengdu',                 'China',          'APAC'),
(32, 'Istanbul',                'Turkey',         'Europe'),
(33, 'Chiba',                   'Japan',          'APAC'),
(34, 'Cape Town',               'South Africa',   'Africa'),
(35, 'Shenzhen',                'China',          'APAC'),
(36, 'Washington DC',           'USA',            'North America'),
(37, 'Acapulco',                'Mexico',         'North America'),
(38, 'Santa Cruz de Tenerife',  'Spain',          'Europe'),
(39, 'Beijing',                 'China',          'APAC'),
(40, 'Maastricht',              'Netherlands',    'Europe'),
(41, 'Mumbai',                  'India',          'APAC'),
(42, 'Salt Lake City',          'USA',            'North America'),
(43, 'Rome',                    'Italy',          'Europe'),
(44, 'Oslo',                    'Norway',         'Europe'),
(45, 'Bordeaux',                'France',         'Europe'),
(46, 'Toronto',                 'Canada',         'North America'),
(47, 'Karlsruhe',               'Germany',        'Europe'),
(48, 'Boston',                  'USA',            'North America'),
(49, 'Geneva',                  'Switzerland',    'Europe'),
(50, 'Gdańsk',                  'Poland',         'Europe'),
(51, 'Valencia',                'Spain',          'Europe'),
(52, 'Tampa',                   'USA',            'North America'),
(53, 'Birmingham',              'United Kingdom', 'Europe'),
(54, 'Hamburg',                 'Germany',        'Europe'),
(55, 'Nice',                    'France',         'Europe'),
(56, 'Mexico City',             'Mexico',         'North America'),
(57, 'Dublin',                  'Ireland',        'Europe'),
(58, 'Düsseldorf',              'Germany',        'Europe'),
(59, 'Denver',                  'USA',            'North America'),
(60, 'Seoul',                   'South Korea',    'APAC'),
(61, 'Dallas',                  'USA',            'North America'),
(62, 'Poznań',                  'Poland',         'Europe'),
(63, 'Guangzhou',               'China',          'APAC'),
(64, 'Rio de Janeiro',          'Brazil',         'South America'),
(65, 'Utrecht',                 'Netherlands',    'Europe'),
(66, 'London',                  'United Kingdom', 'Europe'),
(67, 'Anaheim',                 'USA',            'North America'),
(68, 'Milan',                   'Italy',          'Europe'),
(69, 'Frankfurt',               'Germany',        'Europe'),
(70, 'Nashville',               'USA',            'North America'),
(71, 'Gent',                    'Belgium',        'Europe'),
(72, 'Vancouver',               'Canada',         'North America');

-- Sanity check
SELECT region, COUNT(*) AS city_count FROM dim_city GROUP BY region ORDER BY city_count DESC;
